#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/20f06f9724b706887c0fc4d91949fa5cf396472c8a7e0aba736d5f6f6b921d18/contract';
import endContract from '../../snapshots/20f06f9724b706887c0fc4d91949fa5cf396472c8a7e0aba736d5f6f6b921d18/contract.json' with { type: 'json' };
import type { Contract as Start } from '../../snapshots/6e579bb2b50fa9bdc83337bb4f5407245542472fbc742930d29d773dacd75560/contract';
import startContract from '../../snapshots/6e579bb2b50fa9bdc83337bb4f5407245542472fbc742930d29d773dacd75560/contract.json' with { type: 'json' };
import { Migration, MigrationCLI, col, fn, lit, primaryKey } from '@prisma/orm-postgres/migration';

export default class M extends Migration<Start, End> {
  override readonly startContractJson = startContract;
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.addNativeEnumValue({ schema: 'public', typeName: 'AuditAction', value: 'USER_UPDATED' }),
      this.addNativeEnumValue({ schema: 'public', typeName: 'AuditAction', value: 'USER_DELETED' }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'USER_ASSIGNMENTS_TRANSFERRED',
      }),
      this.addNativeEnumValue({ schema: 'public', typeName: 'AuditAction', value: 'MFA_ENABLED' }),
      this.addNativeEnumValue({ schema: 'public', typeName: 'AuditAction', value: 'MFA_DISABLED' }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'REPORT_CARD_PUBLISHED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'REPORT_CARD_SIGNED_OFF',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'REVALUATION_REQUESTED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'REVALUATION_REVIEWED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'BOARD_PACK_CREATED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'PARENT_NOTIFIED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'BACKUP_CREATED',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'AuditAction',
        value: 'BACKUP_RESTORED',
      }),
      this.addNativeEnumValue({ schema: 'public', typeName: 'AuditAction', value: 'CPD_UPDATED' }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'BoardPackStatus',
        members: ['PENDING', 'READY', 'FAILED'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'CpdPlanStatus',
        members: ['PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'EmailOutboxStatus',
        members: ['PENDING', 'SENT', 'FAILED', 'SKIPPED'],
      }),
      this.addNativeEnumValue({ schema: 'public', typeName: 'NotificationType', value: 'DIGEST' }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'NotificationType',
        value: 'REPORT_CARD_READY',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'NotificationType',
        value: 'REVALUATION_UPDATE',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'NotificationType',
        value: 'PARENT_PORTAL',
      }),
      this.addNativeEnumValue({
        schema: 'public',
        typeName: 'NotificationType',
        value: 'CPD_NOTICE',
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'ReportCardStatus',
        members: ['DRAFT', 'PUBLISHED', 'SIGNED_OFF'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'RevaluationStatus',
        members: ['PENDING', 'APPROVED', 'REJECTED', 'COMPLETED'],
      }),
      this.createTable({
        schema: 'public',
        table: 'BoardPack',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('error', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('label', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('manifest', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('readyAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('status', '"BoardPackStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'BoardPackStatus' } },
          }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'CpdAppraisal',
        columns: [
          col('academicYear', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('appraiserId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('comments', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('goalsMet', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('nextGoals', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('overallRating', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('periodLabel', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'CpdCertificate',
        columns: [
          col('certificateNo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('earnedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('hours', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issuedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('provider', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'CpdObservation',
        columns: [
          col('classLabel', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('developmentAreas', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('observedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('observerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rating', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('strengths', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('subjectLabel', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'CpdTrainingPlan',
        columns: [
          col('academicYear', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('completedHours', 'float8', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/float8@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"CpdPlanStatus"', {
            notNull: true,
            default: lit('PLANNED'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'CpdPlanStatus' } },
          }),
          col('targetHours', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'EmailOutbox',
        columns: [
          col('bodyHtml', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('bodyText', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('error', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('kind', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('meta', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('sentAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('status', '"EmailOutboxStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'EmailOutboxStatus' } },
          }),
          col('subject', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('toEmail', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'ExamPaperSchedule',
        columns: [
          col('className', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('endTime', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('maxMarks', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paperDate', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('startTime', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('venue', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'ReportCardRelease',
        columns: [
          col('classSectionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('parentsNotifiedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('publishedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('signedOffAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('signedOffById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"ReportCardStatus"', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ReportCardStatus' } },
          }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'RevaluationRequest',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('feePaid', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('originalMarks', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('requestedById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reviewNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reviewedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('reviewedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revisedMarks', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('status', '"RevaluationStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'RevaluationStatus' } },
          }),
          col('studentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addColumn({
        schema: 'public',
        table: 'School',
        column: col('digestEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
      }),
      this.addColumn({
        schema: 'public',
        table: 'School',
        column: col('emailDigestsEnabled', 'bool', {
          notNull: true,
          default: lit(false),
          codecRef: { codecId: 'pg/bool@1' },
        }),
      }),
      this.addColumn({
        schema: 'public',
        table: 'Student',
        column: col('guardianEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
      }),
      this.addColumn({
        schema: 'public',
        table: 'User',
        column: col('mfaEnabled', 'bool', {
          notNull: true,
          default: lit(false),
          codecRef: { codecId: 'pg/bool@1' },
        }),
      }),
      this.addColumn({
        schema: 'public',
        table: 'User',
        column: col('mfaRecoveryHashes', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
      }),
      this.addColumn({
        schema: 'public',
        table: 'User',
        column: col('mfaSecret', 'text', { codecRef: { codecId: 'pg/text@1' } }),
      }),
      this.addUnique({
        schema: 'public',
        table: 'CpdAppraisal',
        constraint: 'CpdAppraisal_teacherId_academicYear_periodLabel_key',
        columns: ['teacherId', 'academicYear', 'periodLabel'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'ExamPaperSchedule',
        constraint: 'ExamPaperSchedule_examId_subjectId_className_key',
        columns: ['examId', 'subjectId', 'className'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'ReportCardRelease',
        constraint: 'ReportCardRelease_examId_classSectionId_key',
        columns: ['examId', 'classSectionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'RevaluationRequest',
        constraint: 'RevaluationRequest_examId_studentId_subjectId_key',
        columns: ['examId', 'studentId', 'subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'BoardPack',
        index: 'BoardPack_createdById_idx_8bf640ed',
        columns: ['createdById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'BoardPack',
        index: 'BoardPack_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'BoardPack',
        index: 'BoardPack_tenantId_examId_idx_b62d70cd',
        columns: ['tenantId', 'examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'BoardPack',
        index: 'BoardPack_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdAppraisal',
        index: 'CpdAppraisal_appraiserId_idx_e03e7363',
        columns: ['appraiserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdAppraisal',
        index: 'CpdAppraisal_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdAppraisal',
        index: 'CpdAppraisal_tenantId_academicYear_idx_353ef48d',
        columns: ['tenantId', 'academicYear'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdAppraisal',
        index: 'CpdAppraisal_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdCertificate',
        index: 'CpdCertificate_issuedById_idx_c14f1329',
        columns: ['issuedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdCertificate',
        index: 'CpdCertificate_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdCertificate',
        index: 'CpdCertificate_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdCertificate',
        index: 'CpdCertificate_tenantId_teacherId_idx_c6ea84aa',
        columns: ['tenantId', 'teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdObservation',
        index: 'CpdObservation_observerId_idx_102debed',
        columns: ['observerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdObservation',
        index: 'CpdObservation_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdObservation',
        index: 'CpdObservation_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdObservation',
        index: 'CpdObservation_tenantId_teacherId_idx_c6ea84aa',
        columns: ['tenantId', 'teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdTrainingPlan',
        index: 'CpdTrainingPlan_createdById_idx_8bf640ed',
        columns: ['createdById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdTrainingPlan',
        index: 'CpdTrainingPlan_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdTrainingPlan',
        index: 'CpdTrainingPlan_tenantId_academicYear_idx_353ef48d',
        columns: ['tenantId', 'academicYear'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdTrainingPlan',
        index: 'CpdTrainingPlan_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'CpdTrainingPlan',
        index: 'CpdTrainingPlan_tenantId_teacherId_idx_c6ea84aa',
        columns: ['tenantId', 'teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EmailOutbox',
        index: 'EmailOutbox_status_createdAt_idx_58610442',
        columns: ['status', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EmailOutbox',
        index: 'EmailOutbox_tenantId_createdAt_idx_88162366',
        columns: ['tenantId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EmailOutbox',
        index: 'EmailOutbox_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExamPaperSchedule',
        index: 'ExamPaperSchedule_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExamPaperSchedule',
        index: 'ExamPaperSchedule_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExamPaperSchedule',
        index: 'ExamPaperSchedule_tenantId_examId_paperDate_idx_6999b94c',
        columns: ['tenantId', 'examId', 'paperDate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExamPaperSchedule',
        index: 'ExamPaperSchedule_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ReportCardRelease',
        index: 'ReportCardRelease_classSectionId_idx_095a6e92',
        columns: ['classSectionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ReportCardRelease',
        index: 'ReportCardRelease_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ReportCardRelease',
        index: 'ReportCardRelease_signedOffById_idx_9b472f90',
        columns: ['signedOffById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ReportCardRelease',
        index: 'ReportCardRelease_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ReportCardRelease',
        index: 'ReportCardRelease_tenantId_status_idx_d3d04256',
        columns: ['tenantId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_requestedById_idx_f9a56c66',
        columns: ['requestedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_reviewedById_idx_e2835478',
        columns: ['reviewedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_studentId_idx_bf255322',
        columns: ['studentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RevaluationRequest',
        index: 'RevaluationRequest_tenantId_status_idx_d3d04256',
        columns: ['tenantId', 'status'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'BoardPack',
        foreignKey: {
          name: 'BoardPack_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'BoardPack',
        foreignKey: {
          name: 'BoardPack_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'BoardPack',
        foreignKey: {
          name: 'BoardPack_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdAppraisal',
        foreignKey: {
          name: 'CpdAppraisal_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdAppraisal',
        foreignKey: {
          name: 'CpdAppraisal_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdAppraisal',
        foreignKey: {
          name: 'CpdAppraisal_appraiserId_fkey',
          columns: ['appraiserId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdCertificate',
        foreignKey: {
          name: 'CpdCertificate_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdCertificate',
        foreignKey: {
          name: 'CpdCertificate_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdCertificate',
        foreignKey: {
          name: 'CpdCertificate_issuedById_fkey',
          columns: ['issuedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdObservation',
        foreignKey: {
          name: 'CpdObservation_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdObservation',
        foreignKey: {
          name: 'CpdObservation_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdObservation',
        foreignKey: {
          name: 'CpdObservation_observerId_fkey',
          columns: ['observerId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdTrainingPlan',
        foreignKey: {
          name: 'CpdTrainingPlan_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdTrainingPlan',
        foreignKey: {
          name: 'CpdTrainingPlan_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'CpdTrainingPlan',
        foreignKey: {
          name: 'CpdTrainingPlan_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'EmailOutbox',
        foreignKey: {
          name: 'EmailOutbox_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExamPaperSchedule',
        foreignKey: {
          name: 'ExamPaperSchedule_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExamPaperSchedule',
        foreignKey: {
          name: 'ExamPaperSchedule_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExamPaperSchedule',
        foreignKey: {
          name: 'ExamPaperSchedule_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ReportCardRelease',
        foreignKey: {
          name: 'ReportCardRelease_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ReportCardRelease',
        foreignKey: {
          name: 'ReportCardRelease_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ReportCardRelease',
        foreignKey: {
          name: 'ReportCardRelease_classSectionId_fkey',
          columns: ['classSectionId'],
          references: { schema: 'public', table: 'ClassSection', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ReportCardRelease',
        foreignKey: {
          name: 'ReportCardRelease_signedOffById_fkey',
          columns: ['signedOffById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_studentId_fkey',
          columns: ['studentId'],
          references: { schema: 'public', table: 'Student', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_requestedById_fkey',
          columns: ['requestedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RevaluationRequest',
        foreignKey: {
          name: 'RevaluationRequest_reviewedById_fkey',
          columns: ['reviewedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
