-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DEADLINE_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INCOMPLETE_MARKLIST';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'STAFF_NOTICE';
