#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/6e579bb2b50fa9bdc83337bb4f5407245542472fbc742930d29d773dacd75560/contract';
import endContract from '../../snapshots/6e579bb2b50fa9bdc83337bb4f5407245542472fbc742930d29d773dacd75560/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'AuditAction',
        members: [
          'MARK_CHANGED',
          'MARK_DELETED',
          'MARK_SUBMITTED',
          'MARK_APPROVED',
          'MARK_UNAPPROVED',
          'MARK_MODERATED',
          'ACCESS_REQUESTED',
          'ACCESS_APPROVED',
          'ACCESS_REJECTED',
          'USER_CREATED',
          'USER_STATUS_CHANGED',
          'USER_ROLE_CHANGED',
          'USER_PASSWORD_RESET',
          'EXAM_CREATED',
          'EXAM_UPDATED',
          'EXAM_DELETED',
          'SCHOOL_CREATED',
          'SCHOOL_UPDATED',
          'SCHOOL_STATUS_CHANGED',
        ],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'ExamType',
        members: ['UNIT_TEST', 'MID_TERM', 'FINAL'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'MarkEntryAccessKind',
        members: ['LATE_ENTRY', 'EDIT'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'MarkEntryAccessStatus',
        members: ['PENDING', 'APPROVED', 'REJECTED'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'MarkOutcome',
        members: ['SCORED', 'ABSENT', 'EXEMPT', 'WITHHELD'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'MarkStatus',
        members: ['DRAFT', 'SUBMITTED', 'APPROVED'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'NotificationType',
        members: [
          'LATE_ENTRY_REQUESTED',
          'LATE_ENTRY_APPROVED',
          'LATE_ENTRY_REJECTED',
          'EDIT_REQUESTED',
          'EDIT_APPROVED',
          'EDIT_REJECTED',
          'MARKS_SUBMITTED',
          'DEADLINE_REMINDER',
          'INCOMPLETE_MARKLIST',
          'STAFF_NOTICE',
        ],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'Role',
        members: ['PLATFORM_ADMIN', 'PRINCIPAL', 'EXAM_COORDINATOR', 'TEACHER'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'SchoolStatus',
        members: ['ACTIVE', 'SUSPENDED'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'StudentStatus',
        members: ['ACTIVE', 'PROMOTED', 'TRANSFERRED', 'LEFT'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'UserStatus',
        members: ['PENDING', 'ACTIVE', 'REJECTED'],
      }),
      this.createTable({
        schema: 'public',
        table: 'ActivityAudit',
        columns: [
          col('action', '"AuditAction"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'AuditAction' } },
          }),
          col('actorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('meta', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('summary', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('timestamp', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'ClassSection',
        columns: [
          col('className', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('classTeacherId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('section', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Exam',
        columns: [
          col('academicYear', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('consolidationLocked', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('consolidationLockedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('consolidationLockedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('consolidationMaxMarks', 'int4', {
            notNull: true,
            default: lit(100),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('date', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('marksEntryDeadline', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('term', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', '"ExamType"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ExamType' } },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Mark',
        columns: [
          col('enteredById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('marksObtained', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('outcome', '"MarkOutcome"', {
            notNull: true,
            default: lit('SCORED'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'MarkOutcome' } },
          }),
          col('practicalMarks', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('status', '"MarkStatus"', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'MarkStatus' } },
          }),
          col('studentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'MarkAudit',
        columns: [
          col('changedById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('markId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('newValue', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('oldValue', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('timestamp', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        columns: [
          col('classSectionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('kind', '"MarkEntryAccessKind"', {
            notNull: true,
            default: lit('LATE_ENTRY'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'MarkEntryAccessKind' } },
          }),
          col('message', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('requestedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('reviewedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('reviewedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"MarkEntryAccessStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'MarkEntryAccessStatus' } },
          }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Notification',
        columns: [
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('link', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('meta', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('readAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', '"NotificationType"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'NotificationType' } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Period',
        columns: [
          col('endTime', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isBreak', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('startTime', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'PortalAccessLink',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('examId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('label', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('studentIds', 'text[]', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1', many: true },
          }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'PortalAccessLink_studentIds_elem_not_null_43360d76',
            'array_position("studentIds", NULL) IS NULL',
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'RefreshToken',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'School',
        columns: [
          col('address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('affiliationNo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('alternatePhone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('board', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('city', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('distinctionMin', 'float8', {
            notNull: true,
            default: lit(90),
            codecRef: { codecId: 'pg/float8@1' },
          }),
          col('district', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('establishedYear', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('examWeights', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('gradeBands', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('joinCode', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('logoBytes', 'bytea', { codecRef: { codecId: 'pg/bytea@1' } }),
          col('logoMimeType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('motto', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('passPercent', 'float8', {
            notNull: true,
            default: lit(50),
            codecRef: { codecId: 'pg/float8@1' },
          }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('pincode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('principalName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('recognitionNo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shortName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('state', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"SchoolStatus"', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'SchoolStatus' } },
          }),
          col('udiseCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('website', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('workingDays', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Student',
        columns: [
          col('academicYear', 'text', {
            notNull: true,
            default: lit('2025-26'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('classSectionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('dob', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('guardianName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('guardianPhone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('promotedFromId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('rollNo', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"StudentStatus"', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'StudentStatus' } },
          }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('studentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'Subject',
        columns: [
          col('className', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isElective', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('maxMarks', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('practicalMaxMarks', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'TeacherAssignment',
        columns: [
          col('classSectionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'TimetableEntry',
        columns: [
          col('classSectionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('dayOfWeek', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('periodId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('room', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('subjectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('teacherId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenantId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'User',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mustChangePassword', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('role', '"Role"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'Role' } },
          }),
          col('schoolId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"UserStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'UserStatus' } },
          }),
          col('tenantId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'ClassSection',
        constraint: 'ClassSection_tenantId_className_section_key',
        columns: ['tenantId', 'className', 'section'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'Mark',
        constraint: 'Mark_studentId_subjectId_examId_key',
        columns: ['studentId', 'subjectId', 'examId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        constraint: 'MarkEntryAccessRequest_examId_teacherId_classSectionId_subjectId_key',
        columns: ['examId', 'teacherId', 'classSectionId', 'subjectId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'Period',
        constraint: 'Period_tenantId_sortOrder_key',
        columns: ['tenantId', 'sortOrder'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'PortalAccessLink',
        constraint: 'PortalAccessLink_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'RefreshToken',
        constraint: 'RefreshToken_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'School',
        constraint: 'School_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'School',
        constraint: 'School_joinCode_key',
        columns: ['joinCode'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'Student',
        constraint: 'Student_rollNo_classSectionId_key',
        columns: ['rollNo', 'classSectionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        constraint: 'StudentSubjectEnrollment_studentId_subjectId_key',
        columns: ['studentId', 'subjectId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'Subject',
        constraint: 'Subject_tenantId_name_className_key',
        columns: ['tenantId', 'name', 'className'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'TeacherAssignment',
        constraint: 'TeacherAssignment_userId_classSectionId_subjectId_key',
        columns: ['userId', 'classSectionId', 'subjectId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'TimetableEntry',
        constraint: 'TimetableEntry_teacherId_dayOfWeek_periodId_classSectionId_key',
        columns: ['teacherId', 'dayOfWeek', 'periodId', 'classSectionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'TimetableEntry',
        constraint: 'TimetableEntry_classSectionId_dayOfWeek_periodId_key',
        columns: ['classSectionId', 'dayOfWeek', 'periodId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'User',
        constraint: 'User_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'User',
        constraint: 'User_tenantId_schoolId_key',
        columns: ['tenantId', 'schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ActivityAudit',
        index: 'ActivityAudit_actorId_idx_a58f6b4b',
        columns: ['actorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ActivityAudit',
        index: 'ActivityAudit_actorId_timestamp_idx_4ac5f716',
        columns: ['actorId', 'timestamp'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ActivityAudit',
        index: 'ActivityAudit_examId_timestamp_idx_d85efc71',
        columns: ['examId', 'timestamp'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ActivityAudit',
        index: 'ActivityAudit_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ActivityAudit',
        index: 'ActivityAudit_timestamp_idx_a2429bb8',
        columns: ['timestamp'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ClassSection',
        index: 'ClassSection_classTeacherId_idx_a6853519',
        columns: ['classTeacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ClassSection',
        index: 'ClassSection_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Exam',
        index: 'Exam_consolidationLockedById_idx_948b4956',
        columns: ['consolidationLockedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Exam',
        index: 'Exam_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_enteredById_idx_eca39c05',
        columns: ['enteredById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_examId_status_idx_c901306a',
        columns: ['examId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_studentId_idx_bf255322',
        columns: ['studentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Mark',
        index: 'Mark_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkAudit',
        index: 'MarkAudit_changedById_idx_d6e6aadb',
        columns: ['changedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkAudit',
        index: 'MarkAudit_markId_idx_683904f6',
        columns: ['markId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkAudit',
        index: 'MarkAudit_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_classSectionId_idx_095a6e92',
        columns: ['classSectionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_reviewedById_idx_e2835478',
        columns: ['reviewedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_status_requestedAt_idx_27ce3e29',
        columns: ['status', 'requestedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        index: 'MarkEntryAccessRequest_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_userId_readAt_createdAt_idx_9b6c3810',
        columns: ['userId', 'readAt', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Period',
        index: 'Period_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PortalAccessLink',
        index: 'PortalAccessLink_createdById_idx_8bf640ed',
        columns: ['createdById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PortalAccessLink',
        index: 'PortalAccessLink_examId_idx_a57bdadd',
        columns: ['examId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PortalAccessLink',
        index: 'PortalAccessLink_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RefreshToken',
        index: 'RefreshToken_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RefreshToken',
        index: 'RefreshToken_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Student',
        index: 'Student_classSectionId_academicYear_status_idx_5a1f4830',
        columns: ['classSectionId', 'academicYear', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Student',
        index: 'Student_classSectionId_idx_095a6e92',
        columns: ['classSectionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Student',
        index: 'Student_promotedFromId_idx_23892139',
        columns: ['promotedFromId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Student',
        index: 'Student_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        index: 'StudentSubjectEnrollment_studentId_idx_bf255322',
        columns: ['studentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        index: 'StudentSubjectEnrollment_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        index: 'StudentSubjectEnrollment_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Subject',
        index: 'Subject_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TeacherAssignment',
        index: 'TeacherAssignment_classSectionId_idx_095a6e92',
        columns: ['classSectionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TeacherAssignment',
        index: 'TeacherAssignment_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TeacherAssignment',
        index: 'TeacherAssignment_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TeacherAssignment',
        index: 'TeacherAssignment_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_classSectionId_idx_095a6e92',
        columns: ['classSectionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_dayOfWeek_periodId_idx_f9aaee46',
        columns: ['dayOfWeek', 'periodId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_periodId_idx_f0176b8a',
        columns: ['periodId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_subjectId_idx_84df2a1d',
        columns: ['subjectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_teacherId_dayOfWeek_idx_28ae2762',
        columns: ['teacherId', 'dayOfWeek'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_teacherId_idx_bc266660',
        columns: ['teacherId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'TimetableEntry',
        index: 'TimetableEntry_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'User',
        index: 'User_tenantId_idx_c93ed4f1',
        columns: ['tenantId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ActivityAudit',
        foreignKey: {
          name: 'ActivityAudit_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ActivityAudit',
        foreignKey: {
          name: 'ActivityAudit_actorId_fkey',
          columns: ['actorId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ClassSection',
        foreignKey: {
          name: 'ClassSection_classTeacherId_fkey',
          columns: ['classTeacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ClassSection',
        foreignKey: {
          name: 'ClassSection_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Exam',
        foreignKey: {
          name: 'Exam_consolidationLockedById_fkey',
          columns: ['consolidationLockedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Exam',
        foreignKey: {
          name: 'Exam_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Mark',
        foreignKey: {
          name: 'Mark_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Mark',
        foreignKey: {
          name: 'Mark_studentId_fkey',
          columns: ['studentId'],
          references: { schema: 'public', table: 'Student', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Mark',
        foreignKey: {
          name: 'Mark_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Mark',
        foreignKey: {
          name: 'Mark_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Mark',
        foreignKey: {
          name: 'Mark_enteredById_fkey',
          columns: ['enteredById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkAudit',
        foreignKey: {
          name: 'MarkAudit_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkAudit',
        foreignKey: {
          name: 'MarkAudit_markId_fkey',
          columns: ['markId'],
          references: { schema: 'public', table: 'Mark', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkAudit',
        foreignKey: {
          name: 'MarkAudit_changedById_fkey',
          columns: ['changedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_classSectionId_fkey',
          columns: ['classSectionId'],
          references: { schema: 'public', table: 'ClassSection', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MarkEntryAccessRequest',
        foreignKey: {
          name: 'MarkEntryAccessRequest_reviewedById_fkey',
          columns: ['reviewedById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Notification',
        foreignKey: {
          name: 'Notification_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Notification',
        foreignKey: {
          name: 'Notification_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Period',
        foreignKey: {
          name: 'Period_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PortalAccessLink',
        foreignKey: {
          name: 'PortalAccessLink_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PortalAccessLink',
        foreignKey: {
          name: 'PortalAccessLink_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PortalAccessLink',
        foreignKey: {
          name: 'PortalAccessLink_examId_fkey',
          columns: ['examId'],
          references: { schema: 'public', table: 'Exam', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RefreshToken',
        foreignKey: {
          name: 'RefreshToken_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Student',
        foreignKey: {
          name: 'Student_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Student',
        foreignKey: {
          name: 'Student_classSectionId_fkey',
          columns: ['classSectionId'],
          references: { schema: 'public', table: 'ClassSection', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Student',
        foreignKey: {
          name: 'Student_promotedFromId_fkey',
          columns: ['promotedFromId'],
          references: { schema: 'public', table: 'Student', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        foreignKey: {
          name: 'StudentSubjectEnrollment_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        foreignKey: {
          name: 'StudentSubjectEnrollment_studentId_fkey',
          columns: ['studentId'],
          references: { schema: 'public', table: 'Student', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'StudentSubjectEnrollment',
        foreignKey: {
          name: 'StudentSubjectEnrollment_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Subject',
        foreignKey: {
          name: 'Subject_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TeacherAssignment',
        foreignKey: {
          name: 'TeacherAssignment_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TeacherAssignment',
        foreignKey: {
          name: 'TeacherAssignment_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TeacherAssignment',
        foreignKey: {
          name: 'TeacherAssignment_classSectionId_fkey',
          columns: ['classSectionId'],
          references: { schema: 'public', table: 'ClassSection', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TeacherAssignment',
        foreignKey: {
          name: 'TeacherAssignment_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TimetableEntry',
        foreignKey: {
          name: 'TimetableEntry_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TimetableEntry',
        foreignKey: {
          name: 'TimetableEntry_teacherId_fkey',
          columns: ['teacherId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TimetableEntry',
        foreignKey: {
          name: 'TimetableEntry_classSectionId_fkey',
          columns: ['classSectionId'],
          references: { schema: 'public', table: 'ClassSection', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TimetableEntry',
        foreignKey: {
          name: 'TimetableEntry_subjectId_fkey',
          columns: ['subjectId'],
          references: { schema: 'public', table: 'Subject', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'TimetableEntry',
        foreignKey: {
          name: 'TimetableEntry_periodId_fkey',
          columns: ['periodId'],
          references: { schema: 'public', table: 'Period', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'User',
        foreignKey: {
          name: 'User_tenantId_fkey',
          columns: ['tenantId'],
          references: { schema: 'public', table: 'School', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
