-- Detailed school identity, address, and logo for letterheads (per campus)
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "shortName" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "motto" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "logoBytes" BYTEA;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "logoMimeType" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "udiseCode" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "recognitionNo" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "establishedYear" INTEGER;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "principalName" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "district" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "pincode" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "alternatePhone" TEXT;
